name: Deploy AWS Lambda

on: 
  push:
    branches:
      - main
    paths:
      - 'lambda/'

jobs:
  deploy lambda: # name of our job
    runs-on: ubuntu-latest # Sets or specified the runner
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python # Sets up our python environment
        Uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies # Installs any packages
        runs: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS Creds # Sets up our AWS credentials
        uses: aws-actions/configure-aws-credential@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-access-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Deploy Lambda Function # Zips lambda directory and updates lambda function
        run: |
          cd lambdazip -r lambda .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file file://Lambda.zip

      
